-- MySQL Script generated by MySQL Workbench
-- Wed Dec  2 00:24:30 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema LibraryBD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema LibraryBD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LibraryBD` DEFAULT CHARACTER SET utf8 ;
USE `LibraryBD` ;

-- -----------------------------------------------------
-- Table `LibraryBD`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LibraryBD`.`books` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `author` VARCHAR(255) NOT NULL,
  `year` INT UNSIGNED NOT NULL,
  `genre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LibraryBD`.`librarian`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LibraryBD`.`librarian` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `login` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `surname` VARCHAR(255) NOT NULL,
  `department` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LibraryBD`.`catalog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LibraryBD`.`catalog` (
  `book_id` INT NOT NULL,
  `count` INT UNSIGNED NOT NULL,
  `count_left` INT NOT NULL,
  `term` DATETIME NOT NULL,
  PRIMARY KEY (`book_id`),
  UNIQUE INDEX `book id_UNIQUE` (`book_id` ASC) VISIBLE,
  CONSTRAINT `id`
    FOREIGN KEY (`book_id`)
    REFERENCES `LibraryBD`.`books` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LibraryBD`.`reader`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LibraryBD`.`reader` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `surname` VARCHAR(255) NOT NULL,
  `login` VARCHAR(255) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LibraryBD`.`register`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LibraryBD`.`register` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `book_id` INT NOT NULL,
  `reader_id` INT NOT NULL,
  `lend_date` DATETIME NOT NULL,
  `return_date` DATETIME NOT NULL,
  `librarian_id` INT NOT NULL,
  `type` ENUM('library_room', 'season_ticket') NOT NULL DEFAULT 'library_room',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `book id_idx` (`book_id` ASC) VISIBLE,
  INDEX `reader id_idx` (`reader_id` ASC) VISIBLE,
  INDEX `librarian id_idx` (`librarian_id` ASC) VISIBLE,
  CONSTRAINT `book id`
    FOREIGN KEY (`book_id`)
    REFERENCES `LibraryBD`.`catalog` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `reader id`
    FOREIGN KEY (`reader_id`)
    REFERENCES `LibraryBD`.`reader` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `librarian id`
    FOREIGN KEY (`librarian_id`)
    REFERENCES `LibraryBD`.`librarian` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
