-- MySQL Script generated by MySQL Workbench
-- Wed Oct  7 13:49:06 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema LibraryBD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema LibraryBD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LibraryBD` DEFAULT CHARACTER SET utf8 ;
USE `LibraryBD` ;

-- -----------------------------------------------------
-- Table `LibraryBD`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LibraryBD`.`books` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `author` VARCHAR(255) NOT NULL,
  `publisher` VARCHAR(255) NOT NULL,
  `year` INT UNSIGNED NOT NULL,
  `genre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LibraryBD`.`librarian`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LibraryBD`.`librarian` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `department` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LibraryBD`.`catalog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LibraryBD`.`catalog` (
  `book id` INT NOT NULL,
  `count` INT UNSIGNED NOT NULL,
  `count left` INT NOT NULL,
  `department` VARCHAR(255) NOT NULL,
  `term` DATETIME NOT NULL,
  PRIMARY KEY (`book id`),
  UNIQUE INDEX `book id_UNIQUE` (`book id` ASC) VISIBLE,
  CONSTRAINT `id`
    FOREIGN KEY (`book id`)
    REFERENCES `LibraryBD`.`books` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LibraryBD`.`reader`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LibraryBD`.`reader` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `phone number` VARCHAR(12) NULL,
  `birth date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LibraryBD`.`register`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LibraryBD`.`register` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `book id` INT NOT NULL,
  `reader id` INT NOT NULL,
  `lend date` DATETIME NOT NULL,
  `return date` DATETIME NOT NULL,
  `librarian id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `book id_idx` (`book id` ASC) VISIBLE,
  INDEX `reader id_idx` (`reader id` ASC) VISIBLE,
  INDEX `librarian id_idx` (`librarian id` ASC) VISIBLE,
  CONSTRAINT `book id`
    FOREIGN KEY (`book id`)
    REFERENCES `LibraryBD`.`catalog` (`book id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `reader id`
    FOREIGN KEY (`reader id`)
    REFERENCES `LibraryBD`.`reader` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `librarian id`
    FOREIGN KEY (`librarian id`)
    REFERENCES `LibraryBD`.`librarian` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
